# Generated by Django 5.0 on 2024-02-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_route',
            new_name='Route',
        ),
        migrations.RenameModel(
            old_name='Book_ticket',
            new_name='Ticket',
        ),
        migrations.RenameModel(
            old_name='Add_Train',
            new_name='Train',
        ),
    ]
