# Generated by Django 5.0 on 2024-02-19 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0002_rename_add_route_route_rename_book_ticket_ticket_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='route',
            new_name='station_name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='add',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='route',
            new_name='station_name',
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100, null=True)),
                ('fare', models.IntegerField(null=True)),
                ('train', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='railway.train')),
            ],
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
